package com.franklinchen

import org.specs2._
import org.specs2.matcher._

// txt is a package generated by Twirl.
import com.franklinchen.templates.txt

class TwirlSpec extends Specification {
  def is = s2"""
    index text expands correctly $e1
  """

  def e1  = {
    txt.index("hello", "world").toString ==== "hello there, world"
  }
}
